### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ghost** [svenkle/nuget-server#4]
I installed the .msi release on v0.0.6330.3877-pre and installation was fine and server process runs quite nicely on my IIS v8.5.9600.16384 on Windows Server 2012 R2. 
However when I click 

> Click **here** to view your packages.

I get the following NullReferenceException:

![nuget-server](https://user-images.githubusercontent.com/21260335/32620478-bc70430c-c575-11e7-9c43-7a1a7306c17f.png)

**Comment by gowthamrang** [comment]
+1. and I am running the server on windows 10.

**Comment by valeriob** [comment]
+1 😢

**Comment by svenkle** [comment]
To help me diagnose this issue can some who's experiencing the issue do the following and get back to me:

- Open up services.msc and stop the Nuget Server service.
- Navigate on the filesystem to the Nuget Server installed location and run the application as an administrator.
- Verify that the issue is/is not still ocurring

Alternatively you can also try replacing the NuGet server files with the latest pre-release [NuGetServer.zip](https://github.com/svenkle/nuget-server/releases/tag/v0.0.6535.20611-pre).

Regards,
Luke

**Comment by gowthamrang** [comment]
@svenkle : I did follow the procedures  you mentioned above but the issue still keeps occurring.  :(

EDIT:  This issue might be linked to https://stackoverflow.com/questions/15897726/iisexpress-8-cannot-read-configuration-file-redirection-config 
The second answer helped me resolve the issue related to this thread. :)

**Comment by svenkle** [comment]
@gowthamrang [this answer]( https://stackoverflow.com/a/24956548/3652015)? I'll need to look into this further. It seems like IIS is ignoring the application configuration thats setup so that temp files, bin files etc. run inside the application with no external dependencies.

**Comment by gowthamrang** [comment]
@svenkle : Yes

**Comment by opuech** [comment]
I had the same issue on Windows Server 2012 R2, 
> version 'v0.0.6535.20611-pre' fixed it. Thanks !

**Comment by svenkle** [comment]
This issue has been resolved. If the null reference crops up again I will look further into the configuration for IIS Express not loading as expected.
